namespace ComplexBot.Services.Strategies;

/// <summary>
/// Snapshot of a strategy's current state for filter evaluation.
/// Allows filters to make decisions based on indicator values without tight coupling.
/// </summary>
/// <param name="LastSignal">Most recent signal type generated by the strategy</param>
/// <param name="IndicatorValue">Primary indicator value (e.g., RSI value, ADX value)</param>
/// <param name="IsOverbought">Whether strategy indicators show overbought conditions</param>
/// <param name="IsOversold">Whether strategy indicators show oversold conditions</param>
/// <param name="IsTrending">Whether strategy detects a trending market</param>
/// <param name="CustomValues">Additional strategy-specific values</param>
public record StrategyState(
    SignalType? LastSignal,
    decimal? IndicatorValue,
    bool IsOverbought,
    bool IsOversold,
    bool IsTrending,
    Dictionary<string, decimal> CustomValues
)
{
    /// <summary>
    /// Creates an empty state (used when no filter strategy exists).
    /// </summary>
    public static StrategyState Empty => new(
        LastSignal: null,
        IndicatorValue: null,
        IsOverbought: false,
        IsOversold: false,
        IsTrending: false,
        CustomValues: new Dictionary<string, decimal>()
    );
}
